// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(HomestayDbContext))]
    [Migration("20260930074019_UpdateDichVuModel")]
    partial class UpdateDichVuModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.ChiTietDon", b =>
                {
                    b.Property<int>("MaDonDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("MaDonDatPhong", "MaPhong");

                    b.HasIndex("MaPhong");

                    b.ToTable("ChiTietDon", (string)null);
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru", b =>
                {
                    b.Property<int>("MaCoSoLuuTru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCoSoLuuTru"));

                    b.Property<string>("ChinhSach")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GiayPhepKinhDoanhUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GiayPhepKD_URL");

                    b.Property<string>("GiayToAnttUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GiayToANTT_URL");

                    b.Property<string>("GiayToPcccUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GiayToPCCC_URL");

                    b.Property<string>("LoaiHinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaChuCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenCoSoLuuTru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaCoSoLuuTru");

                    b.HasIndex("MaChuCoSoLuuTru");

                    b.ToTable("CoSoLuuTru", (string)null);
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru_TienNghi", b =>
                {
                    b.Property<int>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int>("MaTienNghi")
                        .HasColumnType("int");

                    b.HasKey("MaCoSoLuuTru", "MaTienNghi");

                    b.HasIndex("MaTienNghi");

                    b.ToTable("CoSoLuuTru_TienNghi", (string)null);
                });

            modelBuilder.Entity("API.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("DiemSo")
                        .HasColumnType("int");

                    b.Property<int>("MaDonDatPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiDungDanhGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanHoiChu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaDonDatPhong")
                        .IsUnique();

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("API.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("GiaDichVu")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaDichVu");

                    b.HasIndex("MaCoSoLuuTru");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("API.Models.DonDatPhong", b =>
                {
                    b.Property<int>("MaDonDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonDatPhong"));

                    b.Property<string>("LyDoHoanTien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaGiamGia")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayDen")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayDi")
                        .HasColumnType("date");

                    b.Property<int>("SoNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoTreEm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianYeuCauHoan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDonDatPhong");

                    b.HasIndex("MaGiamGia");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DonDatPhong", (string)null);
                });

            modelBuilder.Entity("API.Models.DonDatPhongDichVu", b =>
                {
                    b.Property<int>("MaDonDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("MaDonDatPhong", "MaDichVu");

                    b.HasIndex("MaDichVu");

                    b.ToTable("DonDatPhongDichVu", (string)null);
                });

            modelBuilder.Entity("API.Models.GiamGia", b =>
                {
                    b.Property<int>("MaGiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiamGia"));

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<int>("PhanTram")
                        .HasColumnType("int");

                    b.Property<string>("TenMa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ToiDa")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("MaGiamGia");

                    b.HasIndex("TenMa")
                        .IsUnique();

                    b.ToTable("GiamGia", (string)null);
                });

            modelBuilder.Entity("API.Models.HinhAnh", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<int?>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<string>("UrlHinhAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaCoSoLuuTru");

                    b.HasIndex("MaPhong");

                    b.ToTable("HinhAnh", null, t =>
                        {
                            t.HasCheckConstraint("CK_HinhAnh_ExclusiveOwner", "(MaCoSoLuuTru IS NOT NULL AND MaPhong IS NULL) OR (MaCoSoLuuTru IS NULL AND MaPhong IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("API.Models.LichLuuTru", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLich");

                    b.HasIndex("MaPhong", "Ngay")
                        .IsUnique();

                    b.ToTable("LichLuuTru", (string)null);
                });

            modelBuilder.Entity("API.Models.LichSuDuyet", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDuyet")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDuyet")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaCoSoLuuTru");

                    b.HasIndex("MaNguoiDuyet");

                    b.ToTable("LichSuDuyet", (string)null);
                });

            modelBuilder.Entity("API.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhong"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoaiPhong");

                    b.ToTable("LoaiPhong", (string)null);
                });

            modelBuilder.Entity("API.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NganHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenNguoiThuHuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("DienThoai")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("API.Models.NhatKyHoatDong", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiDoiTuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaDoiTuong")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MoTaChiTiet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("ThoiGian");

                    b.ToTable("NhatKyHoatDong", (string)null);
                });

            modelBuilder.Entity("API.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<string>("MoTaPhong")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SucChuaNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SucChuaTreEm")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaCoSoLuuTru");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("API.Models.Phong_TienNghi", b =>
                {
                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaTienNghi")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhong", "MaTienNghi");

                    b.HasIndex("MaTienNghi");

                    b.ToTable("Phong_TienNghi", (string)null);
                });

            modelBuilder.Entity("API.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<string>("PTTT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PhanTramHoaHong")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TienGoc")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TienHoaHong")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TienThucNhanChu")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("MaHoaDon");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("API.Models.TienNghiCoSo", b =>
                {
                    b.Property<int>("MaTienNghi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienNghi"));

                    b.Property<string>("TenTienNghi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTienNghi");

                    b.HasIndex("TenTienNghi")
                        .IsUnique();

                    b.ToTable("TienNghiCoSo", (string)null);
                });

            modelBuilder.Entity("API.Models.TienNghiPhong", b =>
                {
                    b.Property<int>("MaTienNghi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienNghi"));

                    b.Property<string>("TenTienNghi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTienNghi");

                    b.HasIndex("TenTienNghi")
                        .IsUnique();

                    b.ToTable("TienNghiPhong", (string)null);
                });

            modelBuilder.Entity("API.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaVaiTro");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("API.Models.ChiTietDon", b =>
                {
                    b.HasOne("API.Models.DonDatPhong", "DonDatPhong")
                        .WithMany("ChiTietDons")
                        .HasForeignKey("MaDonDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Phong", "Phong")
                        .WithMany("ChiTietDons")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonDatPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru", b =>
                {
                    b.HasOne("API.Models.NguoiDung", "ChuCoSoLuuTru")
                        .WithMany("CoSoLuuTrus")
                        .HasForeignKey("MaChuCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuCoSoLuuTru");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru_TienNghi", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany("TienNghis")
                        .HasForeignKey("MaCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.TienNghiCoSo", "TienNghiCoSo")
                        .WithMany()
                        .HasForeignKey("MaTienNghi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("TienNghiCoSo");
                });

            modelBuilder.Entity("API.Models.DanhGia", b =>
                {
                    b.HasOne("API.Models.DonDatPhong", "DonDatPhong")
                        .WithOne("DanhGia")
                        .HasForeignKey("API.Models.DanhGia", "MaDonDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatPhong");
                });

            modelBuilder.Entity("API.Models.DichVu", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany()
                        .HasForeignKey("MaCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoSoLuuTru");
                });

            modelBuilder.Entity("API.Models.DonDatPhong", b =>
                {
                    b.HasOne("API.Models.GiamGia", "GiamGia")
                        .WithMany("DonDatPhongs")
                        .HasForeignKey("MaGiamGia")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Models.NguoiDung", "KhachHang")
                        .WithMany("DonDatPhongs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiamGia");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("API.Models.DonDatPhongDichVu", b =>
                {
                    b.HasOne("API.Models.DichVu", "DichVu")
                        .WithMany("DonDatPhongDichVus")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.DonDatPhong", "DonDatPhong")
                        .WithMany("DonDatPhongDichVus")
                        .HasForeignKey("MaDonDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("DonDatPhong");
                });

            modelBuilder.Entity("API.Models.HinhAnh", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.Phong", "Phong")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaPhong");

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("API.Models.LichLuuTru", b =>
                {
                    b.HasOne("API.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("API.Models.LichSuDuyet", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany("LichSuDuyets")
                        .HasForeignKey("MaCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.NguoiDung", "NguoiDuyet")
                        .WithMany("LichSuDuyets")
                        .HasForeignKey("MaNguoiDuyet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("API.Models.NguoiDung", b =>
                {
                    b.HasOne("API.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("API.Models.NhatKyHoatDong", b =>
                {
                    b.HasOne("API.Models.NguoiDung", "NguoiDung")
                        .WithMany("NhatKyHoatDongs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("API.Models.Phong", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany("Phongs")
                        .HasForeignKey("MaCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.LoaiPhong", "LoaiPhong")
                        .WithMany()
                        .HasForeignKey("MaLoaiPhong")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("API.Models.Phong_TienNghi", b =>
                {
                    b.HasOne("API.Models.Phong", "Phong")
                        .WithMany("TienNghis")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.TienNghiPhong", "TienNghiPhong")
                        .WithMany()
                        .HasForeignKey("MaTienNghi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("TienNghiPhong");
                });

            modelBuilder.Entity("API.Models.ThanhToan", b =>
                {
                    b.HasOne("API.Models.DonDatPhong", "DonDatPhong")
                        .WithOne("ThanhToan")
                        .HasForeignKey("API.Models.ThanhToan", "MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatPhong");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru", b =>
                {
                    b.Navigation("HinhAnhs");

                    b.Navigation("LichSuDuyets");

                    b.Navigation("Phongs");

                    b.Navigation("TienNghis");
                });

            modelBuilder.Entity("API.Models.DichVu", b =>
                {
                    b.Navigation("DonDatPhongDichVus");
                });

            modelBuilder.Entity("API.Models.DonDatPhong", b =>
                {
                    b.Navigation("ChiTietDons");

                    b.Navigation("DanhGia");

                    b.Navigation("DonDatPhongDichVus");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("API.Models.GiamGia", b =>
                {
                    b.Navigation("DonDatPhongs");
                });

            modelBuilder.Entity("API.Models.NguoiDung", b =>
                {
                    b.Navigation("CoSoLuuTrus");

                    b.Navigation("DonDatPhongs");

                    b.Navigation("LichSuDuyets");

                    b.Navigation("NhatKyHoatDongs");
                });

            modelBuilder.Entity("API.Models.Phong", b =>
                {
                    b.Navigation("ChiTietDons");

                    b.Navigation("HinhAnhs");

                    b.Navigation("TienNghis");
                });

            modelBuilder.Entity("API.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
