// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(HomestayDbContext))]
    [Migration("20260914113517_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.ChiTietDon", b =>
                {
                    b.Property<int>("MaDonDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("DonDatPhongMaDonDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("PhongMaPhong")
                        .HasColumnType("int");

                    b.HasKey("MaDonDatPhong", "MaPhong");

                    b.HasIndex("DonDatPhongMaDonDatPhong");

                    b.HasIndex("PhongMaPhong");

                    b.ToTable("ChiTietDon", (string)null);
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru", b =>
                {
                    b.Property<int>("MaCoSoLuuTru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCoSoLuuTru"));

                    b.Property<string>("ChinhSach")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GiayPhepKinhDoanhUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GiayPhepKD_URL");

                    b.Property<string>("GiayToAnttUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GiayToANTT_URL");

                    b.Property<string>("GiayToPcccUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GiayToPCCC_URL");

                    b.Property<string>("LoaiHinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaChuCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenCoSoLuuTru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaCoSoLuuTru");

                    b.HasIndex("MaChuCoSoLuuTru");

                    b.ToTable("CoSoLuuTru", (string)null);
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru_TienNghi", b =>
                {
                    b.Property<int>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int>("MaTienNghi")
                        .HasColumnType("int");

                    b.Property<int>("CoSoLuuTruMaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int>("TienNghiMaTienNghi")
                        .HasColumnType("int");

                    b.HasKey("MaCoSoLuuTru", "MaTienNghi");

                    b.HasIndex("CoSoLuuTruMaCoSoLuuTru");

                    b.HasIndex("TienNghiMaTienNghi");

                    b.ToTable("CoSoLuuTru_TienNghi", (string)null);
                });

            modelBuilder.Entity("API.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("DiemSo")
                        .HasColumnType("int");

                    b.Property<int>("MaDonDatPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungDanhGia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaDonDatPhong")
                        .IsUnique();

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("API.Models.DonDatPhong", b =>
                {
                    b.Property<int>("MaDonDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonDatPhong"));

                    b.Property<int?>("MaGiamGia")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayDen")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayDi")
                        .HasColumnType("date");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int");

                    b.Property<int>("SoNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoTreEm")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDonDatPhong");

                    b.HasIndex("MaGiamGia");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DonDatPhong", (string)null);
                });

            modelBuilder.Entity("API.Models.GiamGia", b =>
                {
                    b.Property<int>("MaGiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiamGia"));

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<int>("PhanTram")
                        .HasColumnType("int");

                    b.Property<string>("TenMa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ToiDa")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("MaGiamGia");

                    b.ToTable("GiamGia", (string)null);
                });

            modelBuilder.Entity("API.Models.HinhAnh", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<int?>("CoSoLuuTruMaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int?>("PhongMaPhong")
                        .HasColumnType("int");

                    b.Property<string>("UrlHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("CoSoLuuTruMaCoSoLuuTru");

                    b.HasIndex("PhongMaPhong");

                    b.ToTable("HinhAnh", (string)null);
                });

            modelBuilder.Entity("API.Models.LichLuuTru", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("date");

                    b.Property<int>("PhongMaPhong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLich");

                    b.HasIndex("PhongMaPhong");

                    b.HasIndex("MaPhong", "Ngay")
                        .IsUnique();

                    b.ToTable("LichLuuTru", (string)null);
                });

            modelBuilder.Entity("API.Models.LichSuDuyet", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDuyet")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDuyet")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaCoSoLuuTru");

                    b.HasIndex("MaNguoiDuyet");

                    b.ToTable("LichSuDuyet", (string)null);
                });

            modelBuilder.Entity("API.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhong"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoaiPhong");

                    b.ToTable("LoaiPhong", (string)null);
                });

            modelBuilder.Entity("API.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaCoSoLuuTru");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("API.Models.Phong_TienNghi", b =>
                {
                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaTienNghi")
                        .HasColumnType("int");

                    b.Property<int>("PhongMaPhong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TienNghiMaTienNghi")
                        .HasColumnType("int");

                    b.HasKey("MaPhong", "MaTienNghi");

                    b.HasIndex("PhongMaPhong");

                    b.HasIndex("TienNghiMaTienNghi");

                    b.ToTable("Phong_TienNghi", (string)null);
                });

            modelBuilder.Entity("API.Models.PhuThu", b =>
                {
                    b.Property<int>("MaPhuThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuThu"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaDonDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenPhuThu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("MaPhuThu");

                    b.HasIndex("MaDonDatPhong");

                    b.ToTable("PhuThu", (string)null);
                });

            modelBuilder.Entity("API.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("DienThoai");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("date");

                    b.Property<string>("ThongTinNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("DienThoai")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaVaiTro");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("API.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("PTTT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TienGoc")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("MaHoaDon");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("API.Models.TienNghi", b =>
                {
                    b.Property<int>("MaTienNghi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienNghi"));

                    b.Property<string>("TenTienNghi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTienNghi");

                    b.ToTable("TienNghi", (string)null);
                });

            modelBuilder.Entity("API.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro", (string)null);

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            MoTa = "Traveler / Guest",
                            TenVaiTro = "GUEST"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MoTa = "Homestay Host / Owner",
                            TenVaiTro = "OWNER"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MoTa = "System Administrator",
                            TenVaiTro = "ADMIN"
                        });
                });

            modelBuilder.Entity("API.Models.ChiTietDon", b =>
                {
                    b.HasOne("API.Models.DonDatPhong", "DonDatPhong")
                        .WithMany("ChiTietDons")
                        .HasForeignKey("DonDatPhongMaDonDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Phong", "Phong")
                        .WithMany("ChiTietDons")
                        .HasForeignKey("PhongMaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru", b =>
                {
                    b.HasOne("API.Models.TaiKhoan", "ChuCoSoLuuTru")
                        .WithMany("CoSoLuuTrus")
                        .HasForeignKey("MaChuCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuCoSoLuuTru");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru_TienNghi", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany("TienNghis")
                        .HasForeignKey("CoSoLuuTruMaCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.TienNghi", "TienNghi")
                        .WithMany()
                        .HasForeignKey("TienNghiMaTienNghi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("TienNghi");
                });

            modelBuilder.Entity("API.Models.DanhGia", b =>
                {
                    b.HasOne("API.Models.DonDatPhong", "DonDatPhong")
                        .WithOne("DanhGia")
                        .HasForeignKey("API.Models.DanhGia", "MaDonDatPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonDatPhong");
                });

            modelBuilder.Entity("API.Models.DonDatPhong", b =>
                {
                    b.HasOne("API.Models.GiamGia", "GiamGia")
                        .WithMany("DonDatPhongs")
                        .HasForeignKey("MaGiamGia")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Models.TaiKhoan", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiamGia");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("API.Models.HinhAnh", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany()
                        .HasForeignKey("CoSoLuuTruMaCoSoLuuTru");

                    b.HasOne("API.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("PhongMaPhong");

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("API.Models.LichLuuTru", b =>
                {
                    b.HasOne("API.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("PhongMaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("API.Models.LichSuDuyet", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany("LichSuDuyets")
                        .HasForeignKey("MaCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.TaiKhoan", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("MaNguoiDuyet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("API.Models.Phong", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany("Phongs")
                        .HasForeignKey("MaCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.LoaiPhong", "LoaiPhong")
                        .WithMany()
                        .HasForeignKey("MaLoaiPhong");

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("API.Models.Phong_TienNghi", b =>
                {
                    b.HasOne("API.Models.Phong", "Phong")
                        .WithMany("TienNghis")
                        .HasForeignKey("PhongMaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.TienNghi", "TienNghi")
                        .WithMany()
                        .HasForeignKey("TienNghiMaTienNghi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("TienNghi");
                });

            modelBuilder.Entity("API.Models.PhuThu", b =>
                {
                    b.HasOne("API.Models.DonDatPhong", "DonDatPhong")
                        .WithMany("PhuThus")
                        .HasForeignKey("MaDonDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatPhong");
                });

            modelBuilder.Entity("API.Models.TaiKhoan", b =>
                {
                    b.HasOne("API.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("API.Models.ThanhToan", b =>
                {
                    b.HasOne("API.Models.DonDatPhong", "DonDatPhong")
                        .WithOne("ThanhToan")
                        .HasForeignKey("API.Models.ThanhToan", "MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonDatPhong");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru", b =>
                {
                    b.Navigation("LichSuDuyets");

                    b.Navigation("Phongs");

                    b.Navigation("TienNghis");
                });

            modelBuilder.Entity("API.Models.DonDatPhong", b =>
                {
                    b.Navigation("ChiTietDons");

                    b.Navigation("DanhGia");

                    b.Navigation("PhuThus");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("API.Models.GiamGia", b =>
                {
                    b.Navigation("DonDatPhongs");
                });

            modelBuilder.Entity("API.Models.Phong", b =>
                {
                    b.Navigation("ChiTietDons");

                    b.Navigation("TienNghis");
                });

            modelBuilder.Entity("API.Models.TaiKhoan", b =>
                {
                    b.Navigation("CoSoLuuTrus");
                });

            modelBuilder.Entity("API.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
