// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(HomestayDbContext))]
    partial class HomestayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("API.Models.ChuCoSoLuuTru", b =>
                {
                    b.Property<int>("MaChuCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ThongTinNganHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChuCoSoLuuTru");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.ToTable("ChuCoSoLuuTrus");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru", b =>
                {
                    b.Property<int>("MaCoSoLuuTru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCoSoLuuTru"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiHinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaChuCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<string>("TenCoSoLuuTru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaCoSoLuuTru");

                    b.HasIndex("MaChuCoSoLuuTru");

                    b.ToTable("CoSoLuuTrus");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru_TienNghi", b =>
                {
                    b.Property<int>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int>("MaTienNghi")
                        .HasColumnType("int");

                    b.Property<int>("CoSoLuuTruMaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int>("TienNghiMaTienNghi")
                        .HasColumnType("int");

                    b.HasKey("MaCoSoLuuTru", "MaTienNghi");

                    b.HasIndex("CoSoLuuTruMaCoSoLuuTru");

                    b.HasIndex("TienNghiMaTienNghi");

                    b.ToTable("CoSoLuuTru_TienNghis");
                });

            modelBuilder.Entity("API.Models.DonDatPhong", b =>
                {
                    b.Property<int>("MaDonDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonDatPhong"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDonDatPhong");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaPhong");

                    b.ToTable("DonDatPhongs");
                });

            modelBuilder.Entity("API.Models.HinhAnh", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<int?>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<string>("UrlHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaCoSoLuuTru");

                    b.HasIndex("MaPhong");

                    b.ToTable("HinhAnhs");
                });

            modelBuilder.Entity("API.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaDonDatPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDonDatPhong");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("API.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("API.Models.LichLuuTru", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLich");

                    b.HasIndex("MaPhong", "Ngay")
                        .IsUnique();

                    b.ToTable("LichLuuTrus");
                });

            modelBuilder.Entity("API.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhong"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoaiPhong");

                    b.ToTable("LoaiPhongs");
                });

            modelBuilder.Entity("API.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<decimal>("GiaHienTai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaCoSoLuuTru");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("API.Models.Phong_TienNghi", b =>
                {
                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaTienNghi")
                        .HasColumnType("int");

                    b.Property<int>("PhongMaPhong")
                        .HasColumnType("int");

                    b.Property<int>("TienNghiMaTienNghi")
                        .HasColumnType("int");

                    b.HasKey("MaPhong", "MaTienNghi");

                    b.HasIndex("PhongMaPhong");

                    b.HasIndex("TienNghiMaTienNghi");

                    b.ToTable("Phong_TienNghis");
                });

            modelBuilder.Entity("API.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("API.Models.TienNghi", b =>
                {
                    b.Property<int>("MaTienNghi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienNghi"));

                    b.Property<string>("TenTienNghi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTienNghi");

                    b.ToTable("TienNghis");
                });

            modelBuilder.Entity("API.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("API.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("API.Models.ChuCoSoLuuTru", b =>
                {
                    b.HasOne("API.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaChuCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru", b =>
                {
                    b.HasOne("API.Models.ChuCoSoLuuTru", "ChuCoSoLuuTru")
                        .WithMany()
                        .HasForeignKey("MaChuCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuCoSoLuuTru");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru_TienNghi", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany()
                        .HasForeignKey("CoSoLuuTruMaCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.TienNghi", "TienNghi")
                        .WithMany()
                        .HasForeignKey("TienNghiMaTienNghi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("TienNghi");
                });

            modelBuilder.Entity("API.Models.DonDatPhong", b =>
                {
                    b.HasOne("API.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("API.Models.HinhAnh", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany()
                        .HasForeignKey("MaCoSoLuuTru");

                    b.HasOne("API.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong");

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("API.Models.HoaDon", b =>
                {
                    b.HasOne("API.Models.DonDatPhong", "DonDatPhong")
                        .WithMany()
                        .HasForeignKey("MaDonDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatPhong");
                });

            modelBuilder.Entity("API.Models.KhachHang", b =>
                {
                    b.HasOne("API.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("API.Models.LichLuuTru", b =>
                {
                    b.HasOne("API.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("API.Models.Phong", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany("Phongs")
                        .HasForeignKey("MaCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.LoaiPhong", "LoaiPhong")
                        .WithMany()
                        .HasForeignKey("MaLoaiPhong");

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("API.Models.Phong_TienNghi", b =>
                {
                    b.HasOne("API.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("PhongMaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.TienNghi", "TienNghi")
                        .WithMany()
                        .HasForeignKey("TienNghiMaTienNghi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("TienNghi");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru", b =>
                {
                    b.Navigation("Phongs");
                });
#pragma warning restore 612, 618
        }
    }
}
