// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(HomestayDbContext))]
    partial class HomestayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int?>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(23, 2)")
                        .HasComputedColumnSql("([DonGia]*[SoLuong])", false);

                    b.HasKey("MaChiTiet")
                        .HasName("PK__ChiTietH__CDF0A114A3164D4E");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("API.Models.ChuCoSoLuuTru", b =>
                {
                    b.Property<int>("MaChuCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<string>("ThongTinNganHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChuCoSoLuuTru")
                        .HasName("PK__ChuCoSoL__BA45510BE67FAC15");

                    b.HasIndex(new[] { "Cccd" }, "UQ__ChuCoSoL__A955A0AAB7449204")
                        .IsUnique();

                    b.ToTable("ChuCoSoLuuTru", (string)null);
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru", b =>
                {
                    b.Property<int>("MaCoSoLuuTru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCoSoLuuTru"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GiayPhepKdUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GiayPhepKD_URL");

                    b.Property<string>("GiayToAnttUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GiayToANTT_URL");

                    b.Property<string>("GiayToPcccUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GiayToPCCC_URL");

                    b.Property<string>("LoaiHinh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Homestay");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaChuCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<string>("TenCoSoLuuTru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiDuyet")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaCoSoLuuTru")
                        .HasName("PK__CoSoLuuT__ED7C1678F326FE9E");

                    b.HasIndex("MaChuCoSoLuuTru");

                    b.ToTable("CoSoLuuTru", (string)null);
                });

            modelBuilder.Entity("API.Models.DanhGium", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("DiemSo")
                        .HasColumnType("int");

                    b.Property<int>("MaDonDatPhong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDungDanhGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanHoiChuCoSoLuuTru")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhGia")
                        .HasName("PK__DanhGia__AA9515BF4288ACD0");

                    b.HasIndex(new[] { "MaDonDatPhong" }, "UQ__DanhGia__F7BDF64622A9B2B1")
                        .IsUnique();

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("API.Models.DonDatPhong", b =>
                {
                    b.Property<int>("MaDonDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonDatPhong"));

                    b.Property<int?>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("NgayDen")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayDi")
                        .HasColumnType("date");

                    b.Property<int?>("SoNguoi")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDonDatPhong")
                        .HasName("PK__DonDatPh__F7BDF64703B8AFAB");

                    b.HasIndex("MaCoSoLuuTru");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaPhong");

                    b.ToTable("DonDatPhong", (string)null);
                });

            modelBuilder.Entity("API.Models.HinhAnh", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<int?>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<string>("UrlHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHinhAnh")
                        .HasName("PK__HinhAnh__A9C37A9BF11BCA99");

                    b.HasIndex("MaCoSoLuuTru");

                    b.HasIndex("MaPhong");

                    b.ToTable("HinhAnh", (string)null);
                });

            modelBuilder.Entity("API.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int?>("MaDonDatPhong")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDon__835ED13B867BCACF");

                    b.HasIndex("MaDonDatPhong");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("API.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KhachHan__88D2F0E54E69A6E4");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("API.Models.LichLuuTru", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<int?>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Ngay")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Trống");

                    b.HasKey("MaLich")
                        .HasName("PK__LichLuuT__728A9AE9008A3495");

                    b.HasIndex(new[] { "MaCoSoLuuTru", "Ngay" }, "UQ_LichHomestay_Ngay")
                        .IsUnique()
                        .HasFilter("[MaCoSoLuuTru] IS NOT NULL");

                    b.HasIndex(new[] { "MaPhong", "Ngay" }, "UQ_LichPhong_Ngay")
                        .IsUnique()
                        .HasFilter("[MaPhong] IS NOT NULL");

                    b.ToTable("LichLuuTru", (string)null);
                });

            modelBuilder.Entity("API.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhong"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenLoaiPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoaiPhong")
                        .HasName("PK__LoaiPhon__2302121759892A37");

                    b.ToTable("LoaiPhong", (string)null);
                });

            modelBuilder.Entity("API.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<decimal?>("GiaHienTai")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int?>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaPhong")
                        .HasName("PK__Phong__20BD5E5BE22A6455");

                    b.HasIndex("MaCoSoLuuTru");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("API.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VaiTro")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaTaiKhoan")
                        .HasName("PK__TaiKhoan__AD7C6529A22F8D9F");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__TaiKhoan__55F68FC0651FA140")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "UQ__TaiKhoan__5C7E359E06BB0A97")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__TaiKhoan__A9D105348E21A727")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("API.Models.TienNghi", b =>
                {
                    b.Property<int>("MaTienNghi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienNghi"));

                    b.Property<string>("TenTienNghi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTienNghi")
                        .HasName("PK__TienNghi__ED7B8F4D6A96D1D7");

                    b.ToTable("TienNghi", (string)null);
                });

            modelBuilder.Entity("CoSoLuuTruTienNghi", b =>
                {
                    b.Property<int>("MaCoSoLuuTru")
                        .HasColumnType("int");

                    b.Property<int>("MaTienNghi")
                        .HasColumnType("int");

                    b.HasKey("MaCoSoLuuTru", "MaTienNghi")
                        .HasName("PK__CoSoLuuT__23ABAE8CC4C28605");

                    b.HasIndex("MaTienNghi");

                    b.ToTable("CoSoLuuTru_TienNghi", (string)null);
                });

            modelBuilder.Entity("PhongTienNghi", b =>
                {
                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaTienNghi")
                        .HasColumnType("int");

                    b.HasKey("MaPhong", "MaTienNghi")
                        .HasName("PK__Phong_Ti__EE6AE6AF68B697AC");

                    b.HasIndex("MaTienNghi");

                    b.ToTable("Phong_TienNghi", (string)null);
                });

            modelBuilder.Entity("API.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("API.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .HasConstraintName("FK__ChiTietHo__MaHoa__5FB337D6");

                    b.Navigation("MaHoaDonNavigation");
                });

            modelBuilder.Entity("API.Models.ChuCoSoLuuTru", b =>
                {
                    b.HasOne("API.Models.TaiKhoan", "MaChuCoSoLuuTruNavigation")
                        .WithOne("ChuCoSoLuuTru")
                        .HasForeignKey("API.Models.ChuCoSoLuuTru", "MaChuCoSoLuuTru")
                        .IsRequired()
                        .HasConstraintName("FK__ChuCoSoLu__MaChu__440B1D61");

                    b.Navigation("MaChuCoSoLuuTruNavigation");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru", b =>
                {
                    b.HasOne("API.Models.ChuCoSoLuuTru", "MaChuCoSoLuuTruNavigation")
                        .WithMany("CoSoLuuTrus")
                        .HasForeignKey("MaChuCoSoLuuTru")
                        .HasConstraintName("FK__CoSoLuuTr__MaChu__46E78A0C");

                    b.Navigation("MaChuCoSoLuuTruNavigation");
                });

            modelBuilder.Entity("API.Models.DanhGium", b =>
                {
                    b.HasOne("API.Models.DonDatPhong", "MaDonDatPhongNavigation")
                        .WithOne("DanhGium")
                        .HasForeignKey("API.Models.DanhGium", "MaDonDatPhong")
                        .IsRequired()
                        .HasConstraintName("FK__DanhGia__MaDonDa__797309D9");

                    b.Navigation("MaDonDatPhongNavigation");
                });

            modelBuilder.Entity("API.Models.DonDatPhong", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "MaCoSoLuuTruNavigation")
                        .WithMany("DonDatPhongs")
                        .HasForeignKey("MaCoSoLuuTru")
                        .HasConstraintName("FK__DonDatPho__MaCoS__5441852A");

                    b.HasOne("API.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("DonDatPhongs")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__DonDatPho__MaKha__534D60F1");

                    b.HasOne("API.Models.Phong", "MaPhongNavigation")
                        .WithMany("DonDatPhongs")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK__DonDatPho__MaPho__5535A963");

                    b.Navigation("MaCoSoLuuTruNavigation");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("API.Models.HinhAnh", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "MaCoSoLuuTruNavigation")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaCoSoLuuTru")
                        .HasConstraintName("FK__HinhAnh__MaCoSoL__74AE54BC");

                    b.HasOne("API.Models.Phong", "MaPhongNavigation")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK__HinhAnh__MaPhong__75A278F5");

                    b.Navigation("MaCoSoLuuTruNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("API.Models.HoaDon", b =>
                {
                    b.HasOne("API.Models.DonDatPhong", "MaDonDatPhongNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaDonDatPhong")
                        .HasConstraintName("FK__HoaDon__MaDonDat__5BE2A6F2");

                    b.Navigation("MaDonDatPhongNavigation");
                });

            modelBuilder.Entity("API.Models.KhachHang", b =>
                {
                    b.HasOne("API.Models.TaiKhoan", "MaKhachHangNavigation")
                        .WithOne("KhachHang")
                        .HasForeignKey("API.Models.KhachHang", "MaKhachHang")
                        .IsRequired()
                        .HasConstraintName("FK__KhachHang__MaKha__403A8C7D");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("API.Models.LichLuuTru", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "MaCoSoLuuTruNavigation")
                        .WithMany("LichLuuTrus")
                        .HasForeignKey("MaCoSoLuuTru")
                        .HasConstraintName("FK__LichLuuTr__MaCoS__6477ECF3");

                    b.HasOne("API.Models.Phong", "MaPhongNavigation")
                        .WithMany("LichLuuTrus")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK__LichLuuTr__MaPho__656C112C");

                    b.Navigation("MaCoSoLuuTruNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("API.Models.Phong", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", "MaCoSoLuuTruNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaCoSoLuuTru")
                        .HasConstraintName("FK__Phong__MaCoSoLuu__4D94879B");

                    b.HasOne("API.Models.LoaiPhong", "MaLoaiPhongNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLoaiPhong")
                        .HasConstraintName("FK__Phong__MaLoaiPho__4F7CD00D");

                    b.Navigation("MaCoSoLuuTruNavigation");

                    b.Navigation("MaLoaiPhongNavigation");
                });

            modelBuilder.Entity("CoSoLuuTruTienNghi", b =>
                {
                    b.HasOne("API.Models.CoSoLuuTru", null)
                        .WithMany()
                        .HasForeignKey("MaCoSoLuuTru")
                        .IsRequired()
                        .HasConstraintName("FK__CoSoLuuTr__MaCoS__6D0D32F4");

                    b.HasOne("API.Models.TienNghi", null)
                        .WithMany()
                        .HasForeignKey("MaTienNghi")
                        .IsRequired()
                        .HasConstraintName("FK__CoSoLuuTr__MaTie__6E01572D");
                });

            modelBuilder.Entity("PhongTienNghi", b =>
                {
                    b.HasOne("API.Models.Phong", null)
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .IsRequired()
                        .HasConstraintName("FK__Phong_Tie__MaPho__70DDC3D8");

                    b.HasOne("API.Models.TienNghi", null)
                        .WithMany()
                        .HasForeignKey("MaTienNghi")
                        .IsRequired()
                        .HasConstraintName("FK__Phong_Tie__MaTie__71D1E811");
                });

            modelBuilder.Entity("API.Models.ChuCoSoLuuTru", b =>
                {
                    b.Navigation("CoSoLuuTrus");
                });

            modelBuilder.Entity("API.Models.CoSoLuuTru", b =>
                {
                    b.Navigation("DonDatPhongs");

                    b.Navigation("HinhAnhs");

                    b.Navigation("LichLuuTrus");

                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("API.Models.DonDatPhong", b =>
                {
                    b.Navigation("DanhGium");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("API.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("API.Models.KhachHang", b =>
                {
                    b.Navigation("DonDatPhongs");
                });

            modelBuilder.Entity("API.Models.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("API.Models.Phong", b =>
                {
                    b.Navigation("DonDatPhongs");

                    b.Navigation("HinhAnhs");

                    b.Navigation("LichLuuTrus");
                });

            modelBuilder.Entity("API.Models.TaiKhoan", b =>
                {
                    b.Navigation("ChuCoSoLuuTru");

                    b.Navigation("KhachHang");
                });
#pragma warning restore 612, 618
        }
    }
}
